language: python
sudo: required
services:
- docker
cache: pip
os:
- linux
python:
- '3.6'
script:
- pip install pipenv
- pipenv install arxiv-marxdown

deploy:
# Deploy commits on working branches to development, named based on the branch
# name.
- provider: script
  script:
    ./make_and_push_image.sh &&
    ./deploy.sh marxdown development
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master && $TRAVIS_BRANCH != develop

# Deploy tagged commits to staging.
- provider: script
  script:
    ./make_and_push_image.sh &&
    ./deploy.sh marxdown staging
  on:
    tags: true


# Deploy the develop branch to development.
- provider: script
  script:
    ./make_and_push_image.sh &&
    ./deploy.sh marxdown development
  on:
    branch: development
