steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        .prep_for_mkdocs.sh
        mkdocs build
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '-d', 'site/', 'gs://arxiv-docs/']
