steps:
  - name: 'python:3.9-bullseye'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        pip install -r mkdocs-requirements.txt
        mkdocs build

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', '-q', 'rsync', '-r', '-d', 'site/', 'gs://arxiv-docs/']
