name: deploy_docs

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.STATIC_CDN_AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTION_CICD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTION_CICD }}
      DEST_DIR: ${{ github.ref }}
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: prep build upload to S3
      run: ./mkdocs/scripts/deploy_to_s3.sh

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      
