site_name: My Docs
plugins:
  - search
  - macros
  - git-show-history-log
  - redirects:
      redirect_maps:
        'hypertex/bugs.md': 'help/hypertex/bugs.md'
        'hypertex/extensions.md': 'help/hypertex/extensions.md'
        'hypertex/index.md': 'help/hypertex/index.md'
theme:
  name: null
  custom_dir: arxiv_doc_theme
  include_search_page: true
repo_name: GitHub
repo_url: https://github.com/arXiv/arxiv-docs
edit_uri: blob/master/mkdocs/docs
